### ISSUE TITLE
If the number of minutes from Jan 1,1970 and to the time given in any of the row is divisible by 10.Display that row(P.S. This issue to be solved only after solving #1,#2,#3 issues.

### ISSUE THREAD

**Issue by jeff10joy** [acmpesuecc/ZodiacKiller#4]
Basically calculate the total number of minutes from Jan 1,1970 to time given in a row under Time.Spotted column.
If that value is divisible by 10,JACKPOT! You caught the killer.

**Comment by abhishek-pes** [comment]
@jeff10joy  I would like to do this
